#pragma once


#define ACTION_INFECT_NONE 0
#define ACTION_INFECT_SEASONAL 1
#define ACTION_INFECT_PANDEMIC 2
#define ACTION_INFECT_BOTH 3

#define STATUS_SUSCEPTIBLE 0
#define STATUS_INFECTED 1
#define STATUS_RECOVERED 2


#define DAY_NOT_INFECTED -1
#define GENERATION_NOT_INFECTED -1
#define INITIAL_DAY 0

#define BUSINESS_TYPE_AFTERSCHOOL 9

const int NUM_WEEKEND_ERRANDS = 3;
const int NUM_WEEKEND_ERRAND_HOURS = 10;